stages:
  - test
  - build
  - migrate
  - deploy

variables:
  DEV_BRANCH: dev
  PROD_BRANCH: main

.build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  environment:
    name: $ENV_NAME
    action: prepare
  script:
    - export CACHE_REPO=${CFA_REGISTRY}/cache
    - >-
      /kaniko/executor
      --cleanup
      --skip-unused-stages
      --cache
      --cache-copy-layers
      --cache-repo "${CACHE_REPO}"
      --target ${TARGET}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CFA_REGISTRY}/${APP_NAME}:${CI_PIPELINE_IID}"
    - echo "IMAGE_TAG=$CI_PIPELINE_IID" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED != "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
      variables:
        ENV_NAME: development
      exists:
        - Dockerfile
    - if: "$CI_COMMIT_BRANCH == $PROD_BRANCH"
      variables:
        ENV_NAME: production
      exists:
        - Dockerfile
      when: manual
    - if: "$CI_COMMIT_REF_PROTECTED"

build-app:
  extends: .build
  variables:
    TARGET: app
    APP_NAME: backend

build-migration:
  extends: .build
  variables:
    TARGET: migration
    APP_NAME: migration

.trigger:
  trigger:
    project: dagora/crypto-for-all/crypto4all-infrastructure
    strategy: depend
  variables:
    TF_VAR_IMAGE_TAG: "$IMAGE_TAG"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED != "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
      variables:
        TG_ENVIRONMENT: dev
    - if: "$CI_COMMIT_BRANCH == $PROD_BRANCH"
      variables:
        TG_ENVIRONMENT: prd
      when: manual

migration:
  stage: migrate
  extends: .trigger
  needs:
    - job: build-migration
  variables:
    TRIGGER_JOB: backend:migration

deploy:
  stage: deploy
  extends: .trigger
  needs:
    - job: build-app
    - job: migration
  variables:
    TRIGGER_JOB: backend:deployment
