stages:
  - test
  - build
  - migrate
  - deploy

variables:
  DEV_BRANCH: dev
  PROD_BRANCH: main

build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  environment:
    name: $ENV_NAME
    action: prepare
  script:
    - >-
      /kaniko/executor
      --cache
      --skip-unused-stages
      --target app
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CFA_REGISTRY}/backend:${CI_PIPELINE_IID}"
    - >-
      /kaniko/executor
      --cache
      --skip-unused-stages
      --target app
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target migration
      --destination "${CFA_REGISTRY}/migration:${CI_PIPELINE_IID}"
    - echo "IMAGE_TAG=$CI_PIPELINE_IID" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED != "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
      variables:
        ENV_NAME: development
      exists:
        - Dockerfile
    - if: "$CI_COMMIT_BRANCH == $PROD_BRANCH"
      variables:
        ENV_NAME: production
      exists:
        - Dockerfile
      when: manual
    - if: "$CI_COMMIT_REF_PROTECTED"

.trigger:
  trigger:
    project: dagora/crypto-for-all/crypto4all-infrastructure
    strategy: depend
  needs:
    - job: build
  variables:
    TF_VAR_IMAGE_TAG: "$IMAGE_TAG"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED != "true"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
      variables:
        TG_ENVIRONMENT: dev
    - if: "$CI_COMMIT_BRANCH == $PROD_BRANCH"
      variables:
        TG_ENVIRONMENT: prd
      when: manual

migration:
  stage: migrate
  extends: .trigger
  variables:
    TRIGGER_JOB: backend:migration

deploy:
  stage: deploy
  extends: .trigger
  needs:
    - !reference [.trigger, needs]
    - job: migration
  variables:
    TRIGGER_JOB: backend:deployment
